### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by emilyxzhou** [robotpt/cordial#18]
The integration tests sometimes fail when executed in the Docker-based action, usually with the error message "AttributeError: CordialManager instance has no attribute '_aws_client'". Although this error is resolved upon re-running the action, the tests should be fixed so we can be sure that errors are caused by modifications to the code, and not the tests themselves.

**Comment by emilyxzhou** [comment]
This issue hasn't appeared since we've made some major changes to the CI workflow, so I'm closing it for now.

**Comment by audrow** [comment]
I saw this again when trying a different way of starting the CI. I think that the tests don't have enough time between running them, so their is some cross-contamination between tests.

**Comment by audrow** [comment]
I'm going to close this again as `docker run` seems to get around the flaky tests, altough I'm not sure why. We can reopen if we test failures popping up again with `docker run`.
