### ISSUE TITLE
Dockerfile should build from source each time

### ISSUE THREAD

**Issue by audrow** [robotpt/cordial#19]
The Dockerfile currently builds from an [image that has had cordial setup in it](https://github.com/robotpt/cordial/blob/aa7b01512af05ec37a7821d8e0dd33064b48c25f/.github/actions/run-tests-action/Dockerfile#L1). I am not sure that tests the current branch, or the even the latest code in cordial. I think that we should build the full container each time that a push is created (i.e., the Dockerfile should start at the ROS kinetic image, install cordial's dependencies, and build cordial). It will take longer, but there are several reasons to do this:
* It can test the current branch
* It will let us know if any dependencies have been updated and break Cordial

I suspect that the reason an image with cordial setup is used is because it allows us to move the Dockerfile from the top directory. We can probably get around the issue by copying the projects contents beneath the Dockerfile (maybe using a symbolic link?) in the Github action. If this turns out to be difficult and the Dockerfile needs to be in the top directory, so be it.

One thing to realize is that when you make a Docker image, it is like a freeze of that container at a specific time. Your Dockerfile is not run in pulling the image. You just get the previous result of each line in the Dockerfile - that's what the layers are when you're pulling an image. These layers are like binary files, and that's why it's faster to pull an image than rebuild that image from a Dockerfile. It is because of this that code added to the image and packages installed will be in the same version when you pull the image at a later time as when you created the image originally.

**Comment by audrow** [comment]
@emilyxzhou, do you have the Dockerfile that you used to make the minimal cordial image? You could make a [Github Gist](https://gist.github.com/) and share the link here, or just paste it directly as a comment in this issue (hopefully, it's not that large).

**Comment by emilyxzhou** [comment]
@audrow, here's the [Dockerfile](https://gist.github.com/emilyxzhou/fc7934aab2ac33ac1197fed265d733d1). I was able to move the action Dockerfile out of the top directory by cloning cordial in the minimal image, and I can do the same in the updated action Dockerfile to keep it in its current directory.
