### ISSUE TITLE
[cordial_manager] Add integration tests

### ISSUE THREAD

**Issue by emilyxzhou** [robotpt/cordial#3]
It's important to have tests so we can ensure things are in a working state and have multiple people contribute. 

### Features
- Uses `rostest`
- Runs on [Travis CI](https://travis-ci.org/)
    - Use AWS client with credentials

### Example tests
- Any messaging (publishers, subscribers, servers, clients, actions)
- Interaction between CordialManager and AwsPollyClient

**Comment by audrow** [comment]
We might consider using Github Actions instead of Travis CI.  [Here](https://www.youtube.com/watch?v=F3wZTDmHCFA) is a brief tutorial, and [here](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) is an article how it can be used with Docker.
